# Generated by Django 4.0.2 on 2022-07-22 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделение',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Ф.И.О')),
                ('job', models.CharField(max_length=70, verbose_name='Должность')),
                ('phone', models.CharField(max_length=70, verbose_name='Телефон номер')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Salarys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=100, verbose_name='Месяц')),
                ('salary', models.CharField(max_length=100, verbose_name='Зарплата')),
                ('bonus', models.CharField(max_length=100, verbose_name='Бонус')),
                ('fine', models.CharField(max_length=100, verbose_name='Штраф')),
                ('total', models.CharField(max_length=100, verbose_name='Итог')),
                ('paid', models.CharField(max_length=100, verbose_name='Выплачено')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.workers', verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Информация о зарплате',
                'verbose_name_plural': 'Информация о зарплате',
            },
        ),
    ]
