# Generated by Django 4.0.2 on 2022-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarys',
            name='total',
        ),
        migrations.AlterField(
            model_name='salarys',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус'),
        ),
        migrations.AlterField(
            model_name='salarys',
            name='fine',
            field=models.IntegerField(default=0, verbose_name='Штраф'),
        ),
        migrations.AlterField(
            model_name='salarys',
            name='paid',
            field=models.IntegerField(default=0, verbose_name='Выплачено'),
        ),
        migrations.AlterField(
            model_name='salarys',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
    ]
