# Generated by Django 4.0.2 on 2022-08-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_salarys_total_alter_salarys_bonus_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделение'},
        ),
        migrations.AlterModelOptions(
            name='salarys',
            options={'verbose_name': 'Зарплаты', 'verbose_name_plural': 'Зарплаты'},
        ),
        migrations.RemoveField(
            model_name='salarys',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='salarys',
            name='fine',
        ),
        migrations.RemoveField(
            model_name='salarys',
            name='paid',
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='salarys',
            name='salary',
            field=models.IntegerField(verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='workers',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.department', verbose_name='Подразделение'),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=100, verbose_name='Месяц')),
                ('fine', models.IntegerField(default=0, verbose_name='Выплачено')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.workers', verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Выплате',
                'verbose_name_plural': 'Выплате',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=100, verbose_name='Месяц')),
                ('bonus', models.IntegerField(default=0, verbose_name='Бонус')),
                ('paid', models.IntegerField(default=0, verbose_name='Штраф')),
                ('full_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.workers', verbose_name='Ф.И.О')),
            ],
            options={
                'verbose_name': 'Бонус и шртаф',
                'verbose_name_plural': 'Бонус и шртаф',
            },
        ),
    ]
