# Generated by Django 4.0.2 on 2022-08-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_department_options_alter_salarys_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='year',
            field=models.CharField(default=2022, max_length=10, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='leave',
            name='year',
            field=models.CharField(default=2022, max_length=10, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='salarys',
            name='year',
            field=models.CharField(default=2022, max_length=10, verbose_name='Год'),
        ),
    ]
