# Generated by Django 4.0.2 on 2022-08-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='total',
            options={'verbose_name': 'Итого', 'verbose_name_plural': 'Итого'},
        ),
    ]
