# Generated by Django 4.0.2 on 2022-09-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_leave_options_alter_workers_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ids',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='workers',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.CreateModel(
            name='Request_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.CharField(max_length=70)),
                ('price', models.BigIntegerField()),
                ('avans', models.BooleanField()),
                ('comment', models.CharField(default='', max_length=2560)),
                ('workers', models.ManyToManyField(to='staff.Total')),
            ],
        ),
    ]
