# Generated by Django 4.0.2 on 2022-09-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_department_ids_workers_telegram_id_request_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='ids',
            field=models.CharField(default='', max_length=70, verbose_name='ID'),
        ),
    ]
