# Generated by Django 4.0.2 on 2022-10-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_department_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('data', models.JSONField(default={})),
            ],
        ),
        migrations.AlterModelOptions(
            name='request_price',
            options={'verbose_name': 'Зарплаты/аванс запрос', 'verbose_name_plural': 'Зарплаты/aванс запрос'},
        ),
        migrations.AddField(
            model_name='request_price',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request_price',
            name='status',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='workers',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='workers',
            name='is_boss',
            field=models.BooleanField(default=False, verbose_name='Начальник отдела'),
        ),
    ]
