# Generated by Django 4.0.2 on 2022-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_data_alter_request_price_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='datetime_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
