# Generated by Django 4.0.2 on 2022-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_leave_datetime_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
