# Generated by Django 4.1.2 on 2022-10-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_user_alter_message_user_telegram_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_telegram_id',
            new_name='user',
        ),
    ]
