# Generated by Django 4.1.2 on 2022-10-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_rename_user_telegram_id_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(default='не отвечено', max_length=150),
        ),
    ]
