# Generated by Django 4.1.2 on 2022-10-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
